//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DENTIST_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcessLevel
    {
        public int code { get; set; }
        public Nullable<int> UserCode { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<byte> AcessLevel1 { get; set; }
    
        public virtual TblUser TblUser { get; set; }
    }
}
