//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DENTIST_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clinic
    {
        public Clinic()
        {
            this.PlanVisits = new HashSet<PlanVisit>();
        }
    
        public byte ClinicCode { get; set; }
        public string ClinicName { get; set; }
        public string Depatrment { get; set; }
        public string RoomNO { get; set; }
        public Nullable<byte> ClinicType { get; set; }
        public string Comment { get; set; }
        public Nullable<bool> deleted { get; set; }
    
        public virtual ClinicType ClinicType1 { get; set; }
        public virtual ICollection<PlanVisit> PlanVisits { get; set; }
    }
}
