//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DENTIST_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class consult
    {
        public int consultCode { get; set; }
        public string Idperson { get; set; }
        public Nullable<int> Persno { get; set; }
        public Nullable<int> Fkvdfamily { get; set; }
        public Nullable<int> Icd10code { get; set; }
        public Nullable<int> Servicescode { get; set; }
        public Nullable<byte> ToothID { get; set; }
        public string introductionDate { get; set; }
        public string introductionTime { get; set; }
        public Nullable<int> ConsultDoctors { get; set; }
        public Nullable<int> Doctorscode { get; set; }
        public Nullable<int> usercode { get; set; }
        public Nullable<bool> deleted { get; set; }
    
        public virtual RecipeService RecipeService { get; set; }
        public virtual TblUser TblUser { get; set; }
    }
}
