//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DENTIST_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class costconfirm_Detail
    {
        public long costconfirmDetailCode { get; set; }
        public Nullable<long> costconfirmHeadCode { get; set; }
        public Nullable<int> Servicescode { get; set; }
        public Nullable<byte> ToothID_old { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<byte> ToothID { get; set; }
    
        public virtual costconfirm_head costconfirm_head { get; set; }
    }
}
