//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DENTIST_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class costconfirm_head
    {
        public costconfirm_head()
        {
            this.costconfirm_Detail = new HashSet<costconfirm_Detail>();
        }
    
        public long costconfirmCode { get; set; }
        public string IDPerson { get; set; }
        public Nullable<int> Persno { get; set; }
        public Nullable<int> Fkvdfamily { get; set; }
        public string VisitDate { get; set; }
        public string Doctorsoutname { get; set; }
        public string Confirmdate { get; set; }
        public string Confirmtime { get; set; }
        public Nullable<int> Doctorscode { get; set; }
        public Nullable<int> usercode { get; set; }
        public string Ipadress { get; set; }
        public Nullable<bool> deleted { get; set; }
        public Nullable<int> relationorderno { get; set; }
        public Nullable<int> Fkvdfamily1 { get; set; }
    
        public virtual ICollection<costconfirm_Detail> costconfirm_Detail { get; set; }
        public virtual TblUser TblUser { get; set; }
    }
}
