//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DENTIST_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class dent_screen2
    {
        public int pk_dent_Screen2 { get; set; }
        public Nullable<int> fk_doctor { get; set; }
        public string FirstScreenDate { get; set; }
        public Nullable<int> fk_vst { get; set; }
        public Nullable<int> fk_vdfamily { get; set; }
        public string DentalSurgeryComment { get; set; }
        public string RestorativeTxComment { get; set; }
        public string RCTComment { get; set; }
        public string PaComment { get; set; }
        public string OtherRadioGraphyComment { get; set; }
        public string OCCLComment { get; set; }
        public string EmergenyTxComment { get; set; }
        public string OrupPathoComment { get; set; }
        public string OtherFindingComment { get; set; }
        public string cheifcomplain { get; set; }
        public string CurettageComment { get; set; }
        public string PerioSxComment { get; set; }
        public string ClComment { get; set; }
        public string TPCom { get; set; }
        public string RctCom { get; set; }
        public string NGCom { get; set; }
        public string OtherCom { get; set; }
        public string ExtractionComment { get; set; }
        public Nullable<int> fk_vdfamily1 { get; set; }
        public Nullable<byte> IllnessHistory { get; set; }
        public Nullable<byte> Pregnant { get; set; }
        public Nullable<byte> BMTStatus { get; set; }
        public Nullable<byte> Outmouth { get; set; }
        public Nullable<byte> TMJ { get; set; }
        public Nullable<byte> mucousmouth { get; set; }
        public Nullable<byte> PeriodentalStatus { get; set; }
        public Nullable<byte> Prosthodonti { get; set; }
        public Nullable<byte> Occlusion { get; set; }
        public Nullable<byte> needlerning { get; set; }
        public Nullable<byte> needborosazh { get; set; }
        public Nullable<byte> needfeloride { get; set; }
        public Nullable<byte> needjerm { get; set; }
        public Nullable<byte> needfishorsilant { get; set; }
        public Nullable<byte> dentalneed { get; set; }
        public Nullable<byte> gharbalgari { get; set; }
        public Nullable<byte> Doctors_Consult { get; set; }
        public string Doctors_Consult_text { get; set; }
        public Nullable<byte> Dentist_Consult { get; set; }
        public string Dentist_Consult_text { get; set; }
        public Nullable<bool> deleted { get; set; }
        public Nullable<int> fk_vdfamily2 { get; set; }
    }
}
