//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DENTIST_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class dent_neededservice
    {
        public int pk_dent_neededService { get; set; }
        public string dent_neededServicedesc { get; set; }
        public string group_s { get; set; }
        public Nullable<byte> group_2 { get; set; }
        public string screen_Services_view { get; set; }
    }
}
