//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DENTIST_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class doctorsService
    {
        public long doctorsServiceCode { get; set; }
        public string Idperson { get; set; }
        public Nullable<int> Persno { get; set; }
        public Nullable<int> Fkvdfamily { get; set; }
        public Nullable<int> Servicescode { get; set; }
        public Nullable<byte> ToothID { get; set; }
        public Nullable<int> Doctorscode { get; set; }
        public Nullable<int> Planvst { get; set; }
        public Nullable<int> Recipeturn { get; set; }
        public Nullable<int> recipeID { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<int> Usercode { get; set; }
        public string Insertdate { get; set; }
        public Nullable<System.TimeSpan> Inserttime { get; set; }
        public Nullable<bool> deleted { get; set; }
        public string Ipadress { get; set; }
        public Nullable<int> relationorderno { get; set; }
        public Nullable<int> ToothID_old { get; set; }
        public Nullable<int> Fkvdfamily1 { get; set; }
        public Nullable<int> Fkvdfamily2 { get; set; }
    }
}
