//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DENTIST_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoctorsWorkTime
    {
        public int DoctorsWorkTimeCode { get; set; }
        public Nullable<int> Doctorscode { get; set; }
        public string Workdate { get; set; }
        public Nullable<System.DateTime> Workdate_eng { get; set; }
        public Nullable<byte> Workshift { get; set; }
        public Nullable<System.TimeSpan> timeFrom { get; set; }
        public Nullable<System.TimeSpan> timeTo { get; set; }
        public string Kind { get; set; }
        public Nullable<int> Usercode { get; set; }
        public Nullable<bool> deleted { get; set; }
    }
}
