//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DENTIST_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventsLog
    {
        public long EventsLogCode { get; set; }
        public string usercode { get; set; }
        public string logdate { get; set; }
        public string logtime { get; set; }
        public Nullable<int> LogCode { get; set; }
        public string Ipadress { get; set; }
        public Nullable<int> changecode { get; set; }
    
        public virtual EventsDescription EventsDescription { get; set; }
    }
}
