//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DENTIST_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventsDescription
    {
        public EventsDescription()
        {
            this.EventsLogs = new HashSet<EventsLog>();
        }
    
        public int LogCode { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<EventsLog> EventsLogs { get; set; }
    }
}
