//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DENTIST_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class full_niocperson
    {
        public int PersNo { get; set; }
        public string fullname { get; set; }
        public string fullname2 { get; set; }
        public string nesbatdesc { get; set; }
        public string companyname { get; set; }
        public string Managementname { get; set; }
        public string BirthDate { get; set; }
        public string ValidCenterZoneDesc { get; set; }
        public string validcenterdesc { get; set; }
        public int IdEmployeeType { get; set; }
        public Nullable<int> Fk_Management { get; set; }
        public string IdPerson { get; set; }
        public Nullable<short> RelationOrderNo { get; set; }
        public int Pk_vdfamily { get; set; }
        public short Fk_Nesbat { get; set; }
        public Nullable<int> Id { get; set; }
        public Nullable<int> TblValidCenterZone_Id { get; set; }
        public string Mobile { get; set; }
        public int Fk_validCenter { get; set; }
        public Nullable<short> IDJobRelated { get; set; }
        public bool Sex { get; set; }
    }
}
