//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DENTIST_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class introduction_Head
    {
        public long introductionCode { get; set; }
        public string Idperson { get; set; }
        public Nullable<int> Persno { get; set; }
        public Nullable<int> Fkvdfamily { get; set; }
        public string Personalcode { get; set; }
        public Nullable<int> Outcentercode { get; set; }
        public string introductionDate { get; set; }
        public Nullable<System.TimeSpan> introductionTime { get; set; }
        public Nullable<int> Doctorscode { get; set; }
        public Nullable<int> introductionkind { get; set; }
        public Nullable<int> usercode { get; set; }
        public Nullable<long> TurnId { get; set; }
        public string ipadress { get; set; }
        public Nullable<bool> deleted { get; set; }
        public Nullable<int> relationorderno { get; set; }
        public Nullable<int> Fkvdfamily1 { get; set; }
    }
}
