//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DENTIST_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Introduction_Detail
    {
        public long IntroductionDetailCode { get; set; }
        public Nullable<long> IntroductionHeadCode { get; set; }
        public Nullable<int> Servicescode { get; set; }
        public Nullable<byte> ToothID1 { get; set; }
        public Nullable<byte> ToothID2 { get; set; }
        public Nullable<byte> ToothID3 { get; set; }
        public Nullable<byte> ToothID4 { get; set; }
        public Nullable<byte> ToothID5 { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<byte> ToothID1_old { get; set; }
    }
}
