//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DENTIST_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Introduction_Comment
    {
        public int Id { get; set; }
        public string Comment { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<bool> deleted { get; set; }
    }
}
