//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DENTIST_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobLocation
    {
        public int Id { get; set; }
        public int TblManagement_Id { get; set; }
        public string companyname { get; set; }
        public int IdentityId { get; set; }
        public string Managementname { get; set; }
    }
}
