//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DENTIST_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicalrest
    {
        public int MedicalrestCode { get; set; }
        public string Idperson { get; set; }
        public Nullable<int> Persno { get; set; }
        public Nullable<int> Fkvdfamily { get; set; }
        public string currentdate { get; set; }
        public string Currenttime { get; set; }
        public string Firstrestdate { get; set; }
        public string Endrestdate { get; set; }
        public string Returnworkdate { get; set; }
        public Nullable<int> Icd10code { get; set; }
        public Nullable<byte> Countofrest { get; set; }
        public Nullable<int> Doctorscode { get; set; }
        public Nullable<int> usercode { get; set; }
        public string comment { get; set; }
        public Nullable<bool> deleted { get; set; }
    }
}
