//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DENTIST_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class NiocPerson
    {
        public string IdPerson { get; set; }
        public System.Guid IDPersonold { get; set; }
        public int PersNo { get; set; }
        public Nullable<short> RelationOrderNo { get; set; }
        public short Fk_Nesbat { get; set; }
        public string Lname { get; set; }
        public string Fname { get; set; }
        public string FatherName { get; set; }
        public Nullable<int> Gender { get; set; }
        public int Fk_validCenterZone { get; set; }
        public int Fk_validCenter { get; set; }
        public bool Deleted { get; set; }
        public int IdEmployeeType { get; set; }
        public string BirthDate { get; set; }
        public Nullable<int> Fk_Management { get; set; }
        public Nullable<int> Fk_Company { get; set; }
        public Nullable<int> Fk_subCompany { get; set; }
        public string Mobile { get; set; }
        public int Pk_vdfamily { get; set; }
        public string NationalCode { get; set; }
        public Nullable<short> IDJobRelated { get; set; }
        public int EntryDate { get; set; }
        public int ExpDate { get; set; }
        public Nullable<short> IDEduDegree { get; set; }
        public int oldPk_vdfamily { get; set; }
        public string CancelDate { get; set; }
        public string IdMaritalStatus { get; set; }
        public string HomePhone { get; set; }
        public string WorkPhone { get; set; }
        public string AddressHome { get; set; }
        public string AddressWork { get; set; }
        public int Fk_EmployeeStatus { get; set; }
        public bool Sex { get; set; }
    }
}
