//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DENTIST_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class outcenter
    {
        public int outcenterCode { get; set; }
        public string outcenterName { get; set; }
        public Nullable<byte> outcenterKind { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<byte> OutCenterdepartment { get; set; }
        public string beginDate { get; set; }
        public Nullable<System.DateTime> beginDate_Eng { get; set; }
        public string Enddate { get; set; }
        public Nullable<System.DateTime> Enddate_Eng { get; set; }
        public Nullable<int> usercode { get; set; }
        public string adress { get; set; }
        public string phone { get; set; }
        public string Comment { get; set; }
        public string outcenternamePrint { get; set; }
        public Nullable<bool> deleted { get; set; }
    
        public virtual OutCenterdepartment OutCenterdepartment1 { get; set; }
        public virtual outcenterKind outcenterKind1 { get; set; }
    }
}
