//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DENTIST_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonTbl
    {
        public System.Guid Id { get; set; }
        public string Fname { get; set; }
        public string Lname { get; set; }
        public string EmployeeInfoTbl_Id { get; set; }
        public bool Deleted { get; set; }
        public string NationalCode { get; set; }
        public short TblRelation_Id { get; set; }
        public Nullable<short> RelationOrderNo { get; set; }
        public bool Sex { get; set; }
        public bool ActualDeleted { get; set; }
        public string BirthDate { get; set; }
        public string FatherFname { get; set; }
        public int TblValidCenter_Id { get; set; }
        public int TblValidCenterCity_Id { get; set; }
        public Nullable<short> TblEduDegree_Id { get; set; }
        public string Mobile { get; set; }
        public Nullable<short> TblMaritalStatus_Id { get; set; }
        public int Pk_vdfamily { get; set; }
        public Nullable<int> ComboTable_Id_sex { get; set; }
        public Nullable<System.DateTime> MiladyBirthDate { get; set; }
        public Nullable<int> LastUpdateDate { get; set; }
        public string LastUpdateTime { get; set; }
        public Nullable<short> IDJobRelated { get; set; }
        public string PostCode { get; set; }
        public string Email { get; set; }
        public Nullable<int> PersNo { get; set; }
        public string ExpDate { get; set; }
        public string ExpBookDate { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
    }
}
