//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DENTIST_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Radio_Services_request_Detail
    {
        public int Code { get; set; }
        public Nullable<int> Radio_Services_request_code { get; set; }
        public Nullable<byte> Radio_services_Code { get; set; }
        public Nullable<int> ServicesCode { get; set; }
        public Nullable<byte> ToothId { get; set; }
        public Nullable<byte> Area { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<bool> deleted { get; set; }
    }
}
