//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DENTIST_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Radio_Services_request
    {
        public int Code { get; set; }
        public string IDPerson { get; set; }
        public Nullable<int> persno { get; set; }
        public Nullable<int> Fkvdfamily { get; set; }
        public string Currentdate { get; set; }
        public string currentTime { get; set; }
        public Nullable<int> DoctorsCode { get; set; }
        public Nullable<int> validcenterzone { get; set; }
        public Nullable<byte> Status1 { get; set; }
        public Nullable<byte> Status2 { get; set; }
        public Nullable<int> Usercode { get; set; }
        public string ipadress { get; set; }
        public Nullable<bool> deleted { get; set; }
    }
}
