//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DENTIST_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecipeService
    {
        public RecipeService()
        {
            this.consults = new HashSet<consult>();
        }
    
        public int RecipeServices_code { get; set; }
        public string Recipe_Desc { get; set; }
    
        public virtual ICollection<consult> consults { get; set; }
    }
}
