//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DENTIST_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipe
    {
        public long Turnid { get; set; }
        public string IDPerson { get; set; }
        public Nullable<int> persno { get; set; }
        public string Personelcode { get; set; }
        public Nullable<int> Fkvdfamily { get; set; }
        public string Currentdate { get; set; }
        public string currentTime { get; set; }
        public string Turndate { get; set; }
        public string Turntime { get; set; }
        public Nullable<byte> turnNo { get; set; }
        public Nullable<int> DoctorsCode { get; set; }
        public Nullable<int> Planvisit_code { get; set; }
        public Nullable<byte> Servicescode { get; set; }
        public Nullable<byte> TurnStatus { get; set; }
        public Nullable<byte> Shiftcode { get; set; }
        public Nullable<byte> ToothID_old { get; set; }
        public Nullable<byte> PaientType { get; set; }
        public Nullable<byte> PaientStatus { get; set; }
        public Nullable<int> Usercode { get; set; }
        public Nullable<byte> recipekind { get; set; }
        public string ipadress { get; set; }
        public Nullable<int> validcenterzone { get; set; }
        public Nullable<byte> TOOTHID { get; set; }
        public Nullable<int> relationorderno { get; set; }
        public Nullable<byte> turnstatusold { get; set; }
        public Nullable<int> specialityKindCode { get; set; }
        public Nullable<int> age { get; set; }
        public Nullable<int> validcenter { get; set; }
        public Nullable<int> Fkvdfamily1 { get; set; }
    
        public virtual PaientStatu PaientStatu { get; set; }
        public virtual PaientType PaientType1 { get; set; }
        public virtual Shift Shift { get; set; }
        public virtual TurnStatu TurnStatu { get; set; }
    }
}
