//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DENTIST_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Refer_status
    {
        public int Refer_status1 { get; set; }
        public Nullable<int> Refer_code { get; set; }
        public Nullable<byte> Refer_status_code { get; set; }
    }
}
