//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DENTIST_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Refer
    {
        public int Refer_code { get; set; }
        public Nullable<int> Fkvdfamily { get; set; }
        public Nullable<int> PersNo { get; set; }
        public string Refredate { get; set; }
        public string RefreTime { get; set; }
        public Nullable<int> ReferUser { get; set; }
    }
}
