//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DENTIST_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Screen_count
    {
        public int Screen_count_code { get; set; }
        public Nullable<int> doctorscode { get; set; }
        public Nullable<int> shiftcode { get; set; }
        public Nullable<int> Screen_count1 { get; set; }
    }
}
