//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DENTIST_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Services_Group_report
    {
        public byte Services_Group_code_report { get; set; }
        public string Services_Group_Desc_report { get; set; }
        public Nullable<bool> deleted { get; set; }
    }
}
