//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DENTIST_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Services_detail
    {
        public int Services_detail_Code { get; set; }
        public Nullable<int> Services_Head_code { get; set; }
        public string Services_detail_Name { get; set; }
        public Nullable<byte> ServicesTime { get; set; }
        public Nullable<double> K_NO { get; set; }
        public Nullable<double> Kkanoon_K_NO { get; set; }
        public Nullable<double> f16_K_NO { get; set; }
        public Nullable<int> ServiceTypeF16Code { get; set; }
        public Nullable<int> ServiceTypeKanoonCode { get; set; }
        public Nullable<int> TypeScreen_code { get; set; }
        public Nullable<int> Tarefe_code { get; set; }
        public Nullable<byte> Kanal_NO { get; set; }
        public Nullable<byte> Pinaj_NO { get; set; }
        public Nullable<byte> Pinkanal_NO { get; set; }
        public Nullable<byte> Pinamalgam_NO { get; set; }
        public Nullable<byte> Pinkampozit_NO { get; set; }
        public Nullable<bool> ISValid { get; set; }
        public Nullable<bool> Zarib { get; set; }
        public Nullable<bool> report_health { get; set; }
        public Nullable<double> K_NO1 { get; set; }
        public Nullable<bool> ISValid1 { get; set; }
        public Nullable<bool> childzarib { get; set; }
        public Nullable<bool> deleted { get; set; }
    
        public virtual Services_Head Services_Head { get; set; }
    }
}
