//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DENTIST_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shift
    {
        public Shift()
        {
            this.Recipes = new HashSet<Recipe>();
        }
    
        public byte Shiftcode { get; set; }
        public string Shiftname { get; set; }
        public Nullable<System.TimeSpan> Fromtime { get; set; }
        public Nullable<System.TimeSpan> totime { get; set; }
        public Nullable<int> XmlShiftCode { get; set; }
    
        public virtual ICollection<Recipe> Recipes { get; set; }
    }
}
