//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DENTIST_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblEmployeetype
    {
        public int Id { get; set; }
        public string EmployeeTypeDesc { get; set; }
        public Nullable<int> Treaty_Id { get; set; }
        public Nullable<bool> Display { get; set; }
        public string Number { get; set; }
        public Nullable<int> Tartib { get; set; }
        public string empdesc { get; set; }
    }
}
