//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DENTIST_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSubCompany
    {
        public int Id { get; set; }
        public Nullable<int> TblCompany_Id { get; set; }
        public Nullable<int> TblManagement_Id { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
    }
}
