//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DENTIST_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblUser
    {
        public TblUser()
        {
            this.AcessLevels = new HashSet<AcessLevel>();
            this.consults = new HashSet<consult>();
            this.costconfirm_head = new HashSet<costconfirm_head>();
            this.PlanVisits = new HashSet<PlanVisit>();
            this.vacations = new HashSet<vacation>();
        }
    
        public int UserCode { get; set; }
        public Nullable<int> personalNO { get; set; }
        public string Fname { get; set; }
        public string Lname { get; set; }
        public string SN { get; set; }
        public Nullable<byte> GroupCode { get; set; }
        public string DoctorNO { get; set; }
        public Nullable<byte> specialityKindCode { get; set; }
        public Nullable<byte> specialityCode { get; set; }
        public Nullable<bool> Active { get; set; }
        public string EnglishName { get; set; }
        public string title { get; set; }
        public byte[] Image { get; set; }
        public string PersianTitle { get; set; }
        public string phone { get; set; }
        public string mobile { get; set; }
        public string comment { get; set; }
        public Nullable<int> Screen_count { get; set; }
    
        public virtual ICollection<AcessLevel> AcessLevels { get; set; }
        public virtual ICollection<consult> consults { get; set; }
        public virtual ICollection<costconfirm_head> costconfirm_head { get; set; }
        public virtual ICollection<PlanVisit> PlanVisits { get; set; }
        public virtual Speciality Speciality { get; set; }
        public virtual specialityKind specialityKind { get; set; }
        public virtual userKind userKind { get; set; }
        public virtual ICollection<vacation> vacations { get; set; }
    }
}
