//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DENTIST_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class TurnStatu
    {
        public TurnStatu()
        {
            this.Recipes = new HashSet<Recipe>();
        }
    
        public byte TurnStatuscode { get; set; }
        public string TurnStatusName { get; set; }
    
        public virtual ICollection<Recipe> Recipes { get; set; }
    }
}
