//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DENTIST_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class userKind
    {
        public userKind()
        {
            this.TblUsers = new HashSet<TblUser>();
        }
    
        public byte GroupCode { get; set; }
        public string GroupName { get; set; }
    
        public virtual ICollection<TblUser> TblUsers { get; set; }
    }
}
