//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DENTIST_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class vacation
    {
        public int vacationsCode { get; set; }
        public Nullable<int> Doctorscode { get; set; }
        public string vacationType { get; set; }
        public string fromDate { get; set; }
        public Nullable<System.DateTime> fromDate_Eng { get; set; }
        public string Todate { get; set; }
        public Nullable<System.DateTime> Todate_Eng { get; set; }
        public Nullable<int> usercode { get; set; }
        public Nullable<bool> deleted { get; set; }
    
        public virtual TblUser TblUser { get; set; }
    }
}
