//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIHO_DENTIST_SOFTWARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class version
    {
        public int p_Key { get; set; }
        public string Ver_dafater { get; set; }
        public string Ver_Screen { get; set; }
        public string ver_lcd { get; set; }
        public string ver_lab { get; set; }
        public string Ver_Dgs { get; set; }
    }
}
